### ISSUE TITLE
Tracking issue for new API changes for 0.4

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#157]
# Design

There are discussions open discussing the change of design of API so that we can become closer to a superset of CXX and allow to mix and match between. Some of the latest design points are in #156

# Main Steps

And while doing these consider any general refactoring that can occur :-) 

- [x] Rename `make_qobject` to `cxxqt::bridge` #158 
- [ ] ~~Move current definition to be inside an `extern "Qt"` block #159~~
- [x] Remove C++ namespace prefix #160 
- [x] Add namespace support into the macro attribute `cxxqt::bridge(namespace = "rust::object")` #194
- [ ] ~~Change `extract_qobject` / `extract_extern_qt` to respond with a vector and also have the passthrough contents for `extern "C++" / "Rust"` etc~~
- [x] Remove `handle_property_changed` as it won't be used anymore #151 
- [x] Remove QQmlExtensionPlugin helpers for now #152
- [x] Rearrange the generation so that the mod ffi is removed and we move the Qt code to another mod (see the discussion) #162 
- [x] Pass through extern blocks for now so we can get to the next stage #164
- [x] Require the user to define the types they use in the C++ extern, eg `type QPoint = cxx_qt_lib::QPoint` #167
- [x] Change invokable definition to be onto `impl Qt<T>` block #178
- [x] Rename types exposed to C++ to be MyObject and MyObjectRust #179
- [x] Add rust getter method to go from C++ to Rust #181 
- [x] Change opaque helper types to be UniquePtr and have the wrapping occur on the C++ side #165 #166 
- [x] Namespace internal methods so that we don't collide if QObject are in the same namespace #210 
- [x] Combine the Data and RustObj structs (once this has happened we can try https://github.com/ahayzen-KDAB/cxx-qt/tree/cxx-qt-libs-tidy-derives again) #235 
- [x] Add cxx_qt::qobject macro and use RustObj as the struct for the QObject for now #197 #198
- [x] Add the CppObj methods onto the Cpp obj as a method?
- [x] Put the `impl Qt<T>` block onto the Cpp object and update the wrappers to be namespaced free functions #202 
- [x] Add the macros for cxx_qt:::signals etc #180 
- [x] Remove pattern matching and let compiler failures handle typing issues on the C++ side #239 
- [x] Remove pattern matching and let compiler failures handle typing issues on the Rust side #254 
- [x] Move the properties to be own on the Rust side and add the getter/setter/_mut helper #235 
- [x] Move the CppObj helpers to be on the Cpp object (?)
- [x] Once all the cxx-qt stuff uses macros or we can infer it, then passthrough unknown components to the CXX mod
- [X] Consider how to define signals and state which object they are on (either attribute or template) - attribute
- [x] Add the base class to the cxx_qt::qobject macro #214 
- [x] Add mutable getter for properties #267
- [x] Rename properties to prop/prop_mut/set_prop on the Rust side #267
- [x] Add getter/setter/mut for non properties (private fields) #268
- [ ] ~~Can we use Deref for getters of properties so that we can do UniquePtr<T> -> &T in the same way as T -> &T?~~
- [ ] Have a way to specify that a method is overriding a virtual #257 #282 
- [ ] Implement an example listmodel manually #260
- [ ] Improve C++ context API so that it matches nested objects later #276 
- [ ] Update the book for new API changes
- [ ] Remove any branches from cargo.toml's (eg qt-build)
- [ ] Change signals to be immediate now that we have a recursive mutex #281 
- [ ] Use the module name for the generated file name for now, with a macro file_stem to override #283 
- [ ] Split qml-features QML into pages demoing each feature
- [ ] Change include paths to be `cxx-qt-gen/stem.h` and `cxx-qt-lib/stem.h`

# Further independent steps

- [ ] ~~Change CMake to use a tool #146~~
- [x] Build generated C++ with Cargo, simplify CMake (#174, #218)
- [x] Change UpdateRequester to be generic #150 #215

# Stretch improvements (move to 0.5)

- [x] Run whole build from Cargo without CMake #221 
- [ ] (0.5) ~~Have a `cxx_qt_lib::prelude!()` to define a `unsafe extern "C++"` block with all the types in it~~
- [ ] (0.5) ~~Support having a namespace on further objects, such as on the struct for the QObject~~
- [ ] Support multiple QObject's being defined in one block #216 #250 
  - we need to avoid the create_rs etc colliding on the Rust side (we already namespace on the C++ side) but we either need one of these fixed in CXX to support it...
    - allowing for reusing the same Rust type across bridges (so that we could have a mod ffi and a mod internals_my_object sharing the same type but splitting the create_rs module placement) https://github.com/dtolnay/cxx/issues/496
    - being able to define static methods so we could have MyObjectRust::create_rs() https://github.com/dtolnay/cxx/issues/447
    - or we mangle the names ourselves so they don't collide, but having static method support in CXX would be useful in both directions and avoid the extra namespace etc.
- [ ] Support multiple macro mod blocks
- [ ] (0.5) ~~Have the ability to declare a `#[property(getter = "...", setter = "...", notify = "...")]`~~
- [ ] (0.5) ~~Have an attribute on signals to say that that signal already exists ? `enum Signal { #[existing_name="data_changed"] DataChanged }` which is then matched to the existing name on the base class and prove with static asserts or cxx bridge typing~~
- [ ] ~~Investigate how CXX does parsing of syn code to find the macro mods, as we currently pattern match `cxx::bridge` to be the macro when the developer might do `use cxx::bridge; ... #[bridge]`~~
- [ ] Consider if we can define our own structure for parsing - https://docs.rs/syn/1.0.98/syn/parse/index.html#example this might make it easier to define the syntax ?
- [ ] Split macros into cxx-qt-macro then reexport in cxx-qt so that we can cxx_qt::QObject a struct in the cxx_qt definition (see https://users.rust-lang.org/t/solved-is-it-possible-to-reexport-a-proc-macro/16864 )

**Comment by ahayzen-kdab** [comment]
Split the remaining issues into separate tasks.
