### ISSUE TITLE
Decide on useful crates to add as integration features to cxx-qt-lib 

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#292]
Decide on useful crates to add as integration features to cxx-qt-lib.

Any common Rust crates that are either commonly used for parsing data (eg serde) or crates that help with certain types of data (eg colours, or points, rects). We could add any trait implementations to easily go to/from the crate type or implement any traits that parse the data.

These should then be behind feature flags so that `cxx-qt-lib` can be used both with and without serde etc.

- [x] ~`serde` as a feature then impl (de)serialise for types - #425~ - Skipping for 0.5 we can reconsider later if it's worth it
- [x] `rgb` as a feature for QColor - #424 
- [x] `http` ~/ `hyper`~ Uri as a feature for QUrl - #424 
- [x] `url` as a feature for QUrl - #424 
- [x] `time` as a feature Q{Date,Time,DateTime} - #454
- [x] `chorno` as a feature for Q{Date,Time,DateTime} - #454
- [x] `bytes` as a feature for QByteArray (could be lifetime fun here) - #424 
- [ ] ...

#[cfg_attr(feature = "serde_support", derive(Serialize, Deserialize))] allows for conditional derive https://doc.rust-lang.org/reference/conditional-compilation.html This could be used for "trivial" types like QPoint where the struct on the Rust side represents the object correctly.

**Comment by ahayzen-kdab** [comment]
Closed via #454
