### ISSUE TITLE
Improve and investigate error messages

### ISSUE THREAD

**Issue by ahayzen-kdab** [KDAB/cxx-qt#38]
- [x] Investigate why errors from cxx-qt-gen don't point to the span - #455 
- [x] Investigate if CXX errors can be exposed better (eg from cxx-qt-build) - #461
- [x] ~Investigate why macros don't error in IDEs from cxx-qt-gen errors~ (this was because i had `"rust-analyzer.checkOnSave": false,` set)
- [x] Can we get CXX errors to error in IDEs ? - #461 
- [ ] Check if we need to use the dummy env var to improve IDE experience

# Original Description
- Add error messages for invalid invokable input and return types
- Add error messages for invalid property and invokable names
- Consider how other messages we emitted when the macros code is wrong etc

**Comment by ahayzen-kdab** [comment]
https://blog.jetbrains.com/rust/2022/12/05/what-every-rust-developer-should-know-about-macro-support-in-ides/  is relevant here too with the `RUST_IDE_PROC_MACRO_COMPLETION_DUMMY_IDENTIFIER` env var.

**Comment by LeonMatthesKDAB** [comment]
Also see my comment on #455

**Comment by ahayzen-kdab** [comment]
Interestingly internally `cxx_gen` has two options `gen_header` and `gen_implementation` https://github.com/dtolnay/cxx/blob/5ebaee1a1dd668ab48a231890a26bae5fa81888a/gen/src/mod.rs#L58 these then avoid the generation phase https://github.com/dtolnay/cxx/blob/5ebaee1a1dd668ab48a231890a26bae5fa81888a/gen/src/mod.rs#L178

~Say that these were public or we could modify them somehow, this would allow us to pass the tokens through CXX and find out if it was the parsing/checks phase that has failed or the write phase. Which then means if this first phase failed we could stop the build script and emit a warning, then we know that the macro expansion will fail ?~

But as the later write phases don't fail there is actually no advantage here? So if the `generate_header_and_cc` fails this means the same and we should try to warn.

**Comment by ahayzen-kdab** [comment]
Think i've figured it out :sweat_smile:

**Comment by ahayzen-kdab** [comment]
#547 has massively helped with this. I think this issue is done now ?

**Comment by ahayzen-kdab** [comment]
We have separate issues for any remaining tasks.
