### ISSUE TITLE
Tracking issue: Build system refactorings

### ISSUE THREAD

**Issue by LeonMatthesKDAB** [KDAB/cxx-qt#985]
As part of our ongoing investigations in how to improve our build system, we arrived at a new proposal in #983 .

This is the tracking issue for the architecture outlined in this proposal.

ToDo:
- [x] Extract cmake code into a separate repository.
- [x] Fix Windows file locking/synchronization issues.

**Comment by LeonMatthesKDAB** [comment]
Some things to still do are:
- [ ] Extract cmake code into a separate repository.
- [ ] Fix Windows file locking/synchronization issues.
